# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Sapvis(_Azure):
    _type = "sapvis"
    _icon_dir = "resources/azure/sapvis"


class SAPVisAppServerInstance(_Sapvis):
    _icon = "sap-vis-app-server-instance.png"


class SAPVisCentralServiceInstance(_Sapvis):
    _icon = "sap-vis-central-service-instance.png"


class SAPVisDatabaseInstance(_Sapvis):
    _icon = "sap-vis-database-instance.png"


class VirtualInstanceForSAP(_Sapvis):
    _icon = "virtual-instance-for-sap.png"


# Aliases
